feat(v2.11): upgrade handler fixing the escrow accounts balances
terra-money/core pull request #285
Opened 2024-03-19 17:01 UTC by emidev98

This pull request create the upgrade handler for v2.11 which includes updates to the for PFM's escrow accounts balances due the bug that was spotted for PFM in the previous versions. To calculate the balances we used the following tool at the specified commit: https://github.com/strangelove-ventures/escrow-checker/commit/adf0d867e2210c9ff0a27d8dff1c74ed0c8a00dc .

The tool shows two discrepancies the first one on phoenix-1's side and the second discrepancy on the counterpart chain chihuahua-1:
![image](https://github.com/terra-money/core/assets/49301655/c1506839-7742-4fab-9f97-d98276afd89e)
![image](https://github.com/terra-money/core/assets/49301655/2db931cd-b56b-4f9e-8cb8-7c6f8cd38b3b)

2024-03-20 06:20 UTC, javiersuweijie requested changes

2024-03-20 06:20 UTC, javiersuweijie commented on app/upgrades/v2.11/upgrade.go
> +func CreateUpgradeHandler(
make it such that it only applies for phoenix-1

2024-03-21 05:20 UTC, javiersuweijie approved these changes

2024-03-21 19:24 UTC, emidev98 commented
Hey @faddat, are there any other escrows that may not be listed here that we sould check for this upgtrade hanlder?

2024-03-24 07:05 UTC, merged